### ISSUE TITLE
Dependent on ByteDev.Common 5.0.0

### ISSUE THREAD

**Issue by hmqgg** [ByteDev/ByteDev.Giphy#1]
This NuGet package depends on ByteDev.Common 5.0.0.
Users need to install ByteDev.Common 5.0.0 explicitly to make ByteDev.Giphy work.

**Comment by ByteDev** [comment]
Latest version uses the following package references:
    <PackageReference Include="ByteDev.Collections" Version="2.0.0" />
    <PackageReference Include="ByteDev.Common" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />

ByteDev.Giphy, ByteDev.Collections and ByteDev.Common all target netstandard2.0.

**Comment by ByteDev** [comment]
Arr I see, theres something fishy going on. Let me look into it. Thanks

**Comment by ByteDev** [comment]
I switched to using a nuspec file for the package and forgot to add the dependencies.  Get version 3.1.2 from nuget and it should be ok now.
